### ISSUE TITLE
Challenges with 'docker compose up': Backend OperationalError Despite Frontend and Database Running Smoothly

### ISSUE THREAD

**Issue by jungyongji** [Merck/matcher#12]
Hello,

I've been working with the Matcher project and have run into a bit of a snag when using Docker Compose. Although the frontend and database containers seem to be up and running without any issues (as verified by the `docker ps` command), I'm encountering a persistent error with the backend when attempting to integrate all components using `docker compose up`.

Here's a bit more context: When I execute the backend commands individually through Conda (`conda run python ...`), everything works as expected, with no errors. However, this issue arises specifically when I try to bring up the entire setup through Docker Compose.

I'm wondering if there are any additional considerations or configurations that I might be missing, particularly related to Docker Compose's handling of the backend service. Has anyone else encountered a similar issue, or could provide insights into what might be going wrong?

Any guidance or suggestions would be greatly appreciated!

Thank you in advance for your help.

```
$ docker compose up
[+] Running 4/4
 ✔ Network matcher_matcher-network  Created                                                                                                                                   0.1s 
 ✔ Container matcher-database-1     Created                                                                                                                                   0.1s 
 ✔ Container matcher-backend-1      Created                                                                                                                                   0.1s 
 ✔ Container matcher-frontend-1     Created                                                                                                                                   0.1s 
Attaching to matcher-backend-1, matcher-database-1, matcher-frontend-1
matcher-database-1  | The files belonging to this database system will be owned by user "postgres".
matcher-database-1  | This user must also own the server process.
matcher-database-1  | 
matcher-database-1  | The database cluster will be initialized with locale "en_US.utf8".
matcher-database-1  | The default database encoding has accordingly been set to "UTF8".
matcher-database-1  | The default text search configuration will be set to "english".
matcher-database-1  | 
matcher-database-1  | Data page checksums are disabled.
matcher-database-1  | 
matcher-database-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
matcher-database-1  | creating subdirectories ... ok
matcher-database-1  | selecting dynamic shared memory implementation ... posix
matcher-database-1  | selecting default max_connections ... 100
matcher-database-1  | selecting default shared_buffers ... 128MB
matcher-database-1  | selecting default time zone ... Etc/UTC
matcher-database-1  | creating configuration files ... ok
matcher-database-1  | running bootstrap script ... ok
matcher-backend-1   | 
matcher-database-1  | performing post-bootstrap initialization ... ok
matcher-database-1  | initdb: warning: enabling "trust" authentication for local connections
matcher-database-1  | You can change this by editing pg_hba.conf or using the option -A, or
matcher-database-1  | --auth-local and --auth-host, the next time you run initdb.
matcher-database-1  | syncing data to disk ... ok
matcher-database-1  | 
matcher-database-1  | 
matcher-database-1  | Success. You can now start the database server using:
matcher-database-1  | 
matcher-database-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
matcher-database-1  | 
matcher-database-1  | waiting for server to start....2024-01-15 07:52:58.301 UTC [48] LOG:  starting PostgreSQL 13.13 (Debian 13.13-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
matcher-database-1  | 2024-01-15 07:52:58.308 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
matcher-database-1  | 2024-01-15 07:52:58.331 UTC [49] LOG:  database system was shut down at 2024-01-15 07:52:57 UTC
matcher-database-1  | 2024-01-15 07:52:58.344 UTC [48] LOG:  database system is ready to accept connections
matcher-database-1  |  done
matcher-database-1  | server started
matcher-backend-1   | Preparing record 0[07:52:58] SMILES Parse Error: syntax error while parsing: SMILES
matcher-backend-1   | [07:52:58] SMILES Parse Error: Failed parsing SMILES 'SMILES' for input: 'SMILES'
matcher-database-1  | CREATE DATABASE
matcher-database-1  | 
matcher-database-1  | 
matcher-database-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/load-extensions.sh
matcher-database-1  | CREATE EXTENSION
matcher-database-1  |   oid  | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
matcher-database-1  | -------+---------+----------+--------------+----------------+------------+-----------+--------------
matcher-database-1  |  13454 | plpgsql |       10 |           11 | f              | 1.0        |           | 
matcher-database-1  |  16385 | rdkit   |       10 |         2200 | t              | 4.3.0      |           | 
matcher-database-1  | (2 rows)
matcher-database-1  | 
matcher-database-1  | 
matcher-database-1  | 2024-01-15 07:52:58.811 UTC [48] LOG:  received fast shutdown request
matcher-database-1  | waiting for server to shut down....2024-01-15 07:52:58.818 UTC [48] LOG:  aborting any active transactions
matcher-database-1  | 2024-01-15 07:52:58.822 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
matcher-database-1  | 2024-01-15 07:52:58.822 UTC [50] LOG:  shutting down
matcher-database-1  | 2024-01-15 07:52:58.897 UTC [48] LOG:  database system is shut down
matcher-database-1  |  done
matcher-database-1  | server stopped
matcher-database-1  | 
matcher-database-1  | PostgreSQL init process complete; ready for start up.
matcher-database-1  | 
matcher-database-1  | 2024-01-15 07:52:58.961 UTC [1] LOG:  starting PostgreSQL 13.13 (Debian 13.13-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
matcher-database-1  | 2024-01-15 07:52:58.961 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
matcher-database-1  | 2024-01-15 07:52:58.961 UTC [1] LOG:  listening on IPv6 address "::", port 5432
matcher-frontend-1  | [2024-01-15 07:52:58 +0000] [15] [INFO] Starting gunicorn 20.1.0
matcher-frontend-1  | [2024-01-15 07:52:58 +0000] [15] [INFO] Listening at: http://0.0.0.0:8000 (15)
matcher-frontend-1  | [2024-01-15 07:52:58 +0000] [15] [INFO] Using worker: gevent
matcher-frontend-1  | [2024-01-15 07:52:58 +0000] [16] [INFO] Booting worker with pid: 16
matcher-database-1  | 2024-01-15 07:52:58.974 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
matcher-database-1  | 2024-01-15 07:52:58.991 UTC [66] LOG:  database system was shut down at 2024-01-15 07:52:58 UTC
matcher-database-1  | 2024-01-15 07:52:59.005 UTC [1] LOG:  database system is ready to accept connections
matcher-frontend-1  | [2024-01-15 07:52:59 +0000] [17] [INFO] Booting worker with pid: 17
matcher-backend-1   | Started indexing at time = 1705305180.6845496
matcher-backend-1   | Finished loading fragments, seconds taken = 0.0030546188354492188
matcher-backend-1   | Starting to find pairs at 1705305180.6876042
Traceback (most recent call last):
matcher-backend-1   |   File "/opt/./backend/mmpdb/mmpdb.py", line 9, in <module>
matcher-backend-1   |     commandline.main()
matcher-backend-1   |   File "/opt/backend/mmpdb/mmpdblib/commandline.py", line 1089, in main
matcher-backend-1   |     parsed_args.command(parsed_args.subparser, parsed_args)
matcher-backend-1   |   File "/opt/backend/mmpdb/mmpdblib/commandline.py", line 393, in index_command
matcher-backend-1   |     do_index.index_command(parser, args)
matcher-backend-1   |   File "/opt/backend/mmpdb/mmpdblib/do_index.py", line 203, in index_command
matcher-backend-1   |     with index_algorithm.open_mmpa_writer(args.output, format=args.out,
matcher-backend-1   |   File "/opt/backend/mmpdb/mmpdblib/index_algorithm.py", line 1333, in open_mmpa_writer
matcher-backend-1   |     index_writer = index_writers.open_postgres_index_writer(destination, title)
matcher-backend-1   |   File "/opt/backend/mmpdb/mmpdblib/index_writers.py", line 739, in open_postgres_index_writer
matcher-backend-1   |     db = dbutils.open_postgres_database(filename)
matcher-backend-1   |   File "/opt/backend/mmpdb/mmpdblib/dbutils.py", line 155, in open_postgres_database
matcher-backend-1   |     conn = psycopg2.connect(
matcher-backend-1   |   File "/opt/conda/envs/matcher-api/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
matcher-backend-1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
matcher-backend-1   | psycopg2.OperationalError: timeout expired
matcher-backend-1   | 
matcher-backend-1   | ERROR conda.cli.main_run:execute(47): `conda run python ./backend/mmpdb/mmpdb.py index ./backend/initialize_db/test_structures.fragments -o public$postgres` failed. (See above for error)
```

```
$ docker ps
CONTAINER ID   IMAGE              COMMAND                  CREATED         STATUS         PORTS                                       NAMES
2887c1c6c6a2   matcher-frontend   "conda run --no-capt…"   8 seconds ago   Up 6 seconds   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   matcher-frontend-1
cc8b51c6d099   matcher-backend    "bash -c 'echo $RUN_…"   8 seconds ago   Up 6 seconds   0.0.0.0:8001->8001/tcp, :::8001->8001/tcp   matcher-backend-1
4428773eea48   matcher-database   "docker-entrypoint.s…"   8 seconds ago   Up 6 seconds   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp   matcher-database-1
```

```
$ conda run python ./backend/mmpdb/mmpdb.py index ./backend/initialize_db/test_structures.fragments -o public$postgres
Started indexing at time = 1705305537.7112198
Finished loading fragments, seconds taken = 0.0006251335144042969
Starting to find pairs at 1705305537.711845
Starting to write pairs at 1705305537.901698

```

**Comment by hooveran** [comment]
Hi @jungyongji ,

Thanks for reporting this issue. One possibility is a timing issue, where the backend container is attempting to write to the DB container before it's ready to accept connections. I went ahead and updated the code to try to prevent this scenario.

Could you please pull the newest version of the `main` branch, and give it a try again? I'd recommend using the below commands (note that using the --volumes flag deletes your previous matcher DB data, but this helps prevent issues by starting from a clean slate):

```
docker-compose down --volumes && \
docker-compose build && \
docker-compose up --force-recreate
```

**Comment by jungyongji** [comment]
I recently encountered an issue after accessing http://0.0.0.0:8000/, related to a JSON type error.

```
matcher-frontend-1  | ERROR:frontend.frontend_api:Exception on /dash/_dash-update-component [POST]
matcher-frontend-1  | Traceback (most recent call last):
matcher-frontend-1  |   File "/opt/conda/envs/matcher-frontend/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
matcher-frontend-1  |     response = self.full_dispatch_request()
matcher-frontend-1  |   File "/opt/conda/envs/matcher-frontend/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
matcher-frontend-1  |     rv = self.handle_user_exception(e)
matcher-frontend-1  |   File "/opt/conda/envs/matcher-frontend/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
matcher-frontend-1  |     rv = self.dispatch_request()
matcher-frontend-1  |   File "/opt/conda/envs/matcher-frontend/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
matcher-frontend-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
matcher-frontend-1  |   File "/opt/conda/envs/matcher-frontend/lib/python3.9/site-packages/dash/dash.py", line 1265, in dispatch
matcher-frontend-1  |     ctx.run(
matcher-frontend-1  |   File "/opt/conda/envs/matcher-frontend/lib/python3.9/site-packages/dash/_callback.py", line 450, in add_context
matcher-frontend-1  |     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
matcher-frontend-1  |   File "/home/jyji/matcher/frontend/pages/common/callbacks.py", line 178, in instantiate_output_elements
matcher-frontend-1  |     pair_data = json.loads(pair_data)
matcher-frontend-1  |   File "/opt/conda/envs/matcher-frontend/lib/python3.9/json/__init__.py", line 339, in loads
matcher-frontend-1  |     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
matcher-frontend-1  | TypeError: the JSON object must be str, bytes or bytearray, not list
```

I'm wondering if I need to modify the code in the instantiate_output_elements method within the /home/jyji/matcher/frontend/pages/common/callbacks.py script. This error seems to arise because the file format is a list rather than a string. Is this a common issue that others have experienced?

For your information, I'm currently using the Docker Compose command, not docker-compose. Could this be a contributing factor to the problem?

**Comment by hooveran** [comment]
Hi @jungyongji ,

Why are you trying to access  http://0.0.0.0:8000/ -- are you navigating to this address in a browser, and expecting normal functioning of the app? If that's the case, you shouldn't be navigating to http://0.0.0.0:8000/ (which in my experience will not lead to the desired functionality), and instead you should be navigating to http://localhost:8000, as is written in [the README](https://github.com/Merck/matcher/blob/main/README.md), which works for me to give expected behavior of loading the app's frontend client in the browser.

One test you can run is to navigate to http://localhost:8000/snap/1, and you should see the table below:

![image](https://github.com/Merck/matcher/assets/111536382/c445b6c2-913e-4467-bec1-be7c12c3ba9a)

It shouldn't matter whether you are using `docker-compose` or `docker compose`, this convention is based on the version of Docker that you are using, and otherwise has not had an effect on the functioning of the app in my experience.

Could you confirm that the code in the current `main` branch (as of the time of this post) works on your end, in terms of launching the app with docker compose? At least from your error message, it seems like the code, at least this file: `"/home/jyji/matcher/frontend/pages/common/callbacks.py"` is not running in a container, but it would if using the default docker compose configuration.

That being said, the exception you pasted does occur on page load (even when everything is working as expected with docker compose), and is something we should fix, but as far as I can tell has no effect on the desired functionality of the app.

**Comment by jungyongji** [comment]
Dear @hooveran,

I wanted to extend my deepest gratitude for your invaluable assistance on the GitHub issue regarding the 'docker compose up' challenges in the Matcher project. Your insightful guidance and prompt resolution not only addressed the technical difficulties but also contributed significantly to the project's advancement. Your expertise and willingness to help are truly appreciated.

Warm regards,
jungyongji
